from main_carregar import xp , cofre, vida, vida1, dano, armadura,carnes,life_potion ,diamante ,ouro ,pedra,perola ,chifre ,peixe_p,peixe_m,peixe_g,picareta,maça_dourada,medicina,olho_de_zumbi, ruby,xpl,maça,epic_perola,hyper_perola,epic_chifre,hyper_chifre, mundo 
from main import user

def save():
  file = open(user+'.txt','w+') 
  file.write(f'{carnes}'+',carnes\n')
  file.write(f'{pedra}'+',pedra\n')
  file.write(f'{ouro}'+',ouro\n')
  file.write(f'{diamante}'+',diamante\n')
  file.write(f'{ruby}'+',ruby\n')
  file.write(f'{chifre}'+',chifre\n')
  file.write(f'{perola}'+',perola\n')
  file.write(f'{olho_de_zumbi}'+',olho_de_zumbi\n')
  file.write(f'{life_potion}'+',life_potion\n')
  file.write(f'{peixe_p}'+',peixe_p\n')
  file.write(f'{peixe_m}'+ ',peixe_m\n')
  file.write(f'{peixe_g}' +',peixe_g\n')
  file.write(f'{xp}' +',xp\n')
  file.write(f'{cofre}' +',cofre\n')
  file.write(f'{vida1}' +',vida1\n')
  file.write(f'{dano}' +',dano\n')
  file.write(f'{armadura}' +',armadura\n')
  file.write(f'{picareta}' +',picareta\n')
  file.write(f'{medicina}' +',medicina\n')
  file.write(f'{maça_dourada}' +',maça_dourada\n')
  file.write(f'{vida}' +',vida\n')
  file.write(f'{xpl}' +',xpl\n')
  file.write(f'{maça}' +',maça\n')
  file.write(f'{mundo}' +',mundo\n')
  file.write(f'{epic_perola}' +',epic_perola\n')
  file.write(f'{hyper_perola}' +',hyper_perola\n')
  file.write(f'{epic_chifre}' +',epic_chifre\n')
  file.write(f'{hyper_chifre}' +',hyper_chifre')
  file.close()
